/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as Surface3dRouteImport } from './routes/surface-3d'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as RegressionRouteImport } from './routes/regression'
import { Route as ParametricRouteImport } from './routes/parametric'
import { Route as OdeRouteImport } from './routes/ode'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as MultiRouteImport } from './routes/multi'
import { Route as LinkedRouteImport } from './routes/linked'
import { Route as ImplicitRouteImport } from './routes/implicit'
import { Route as GeometryRouteImport } from './routes/geometry'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'

const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const Surface3dRoute = Surface3dRouteImport.update({
  id: '/surface-3d',
  path: '/surface-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const RegressionRoute = RegressionRouteImport.update({
  id: '/regression',
  path: '/regression',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametricRoute = ParametricRouteImport.update({
  id: '/parametric',
  path: '/parametric',
  getParentRoute: () => rootRouteImport,
} as any)
const OdeRoute = OdeRouteImport.update({
  id: '/ode',
  path: '/ode',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiRoute = MultiRouteImport.update({
  id: '/multi',
  path: '/multi',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedRoute = LinkedRouteImport.update({
  id: '/linked',
  path: '/linked',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplicitRoute = ImplicitRouteImport.update({
  id: '/implicit',
  path: '/implicit',
  getParentRoute: () => rootRouteImport,
} as any)
const GeometryRoute = GeometryRouteImport.update({
  id: '/geometry',
  path: '/geometry',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/geometry': typeof GeometryRoute
  '/implicit': typeof ImplicitRoute
  '/linked': typeof LinkedRoute
  '/multi': typeof MultiRoute
  '/notebook': typeof NotebookRoute
  '/ode': typeof OdeRoute
  '/parametric': typeof ParametricRoute
  '/regression': typeof RegressionRoute
  '/statistics': typeof StatisticsRoute
  '/surface-3d': typeof Surface3dRoute
  '/systems': typeof SystemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/geometry': typeof GeometryRoute
  '/implicit': typeof ImplicitRoute
  '/linked': typeof LinkedRoute
  '/multi': typeof MultiRoute
  '/notebook': typeof NotebookRoute
  '/ode': typeof OdeRoute
  '/parametric': typeof ParametricRoute
  '/regression': typeof RegressionRoute
  '/statistics': typeof StatisticsRoute
  '/surface-3d': typeof Surface3dRoute
  '/systems': typeof SystemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/geometry': typeof GeometryRoute
  '/implicit': typeof ImplicitRoute
  '/linked': typeof LinkedRoute
  '/multi': typeof MultiRoute
  '/notebook': typeof NotebookRoute
  '/ode': typeof OdeRoute
  '/parametric': typeof ParametricRoute
  '/regression': typeof RegressionRoute
  '/statistics': typeof StatisticsRoute
  '/surface-3d': typeof Surface3dRoute
  '/systems': typeof SystemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/geometry'
    | '/implicit'
    | '/linked'
    | '/multi'
    | '/notebook'
    | '/ode'
    | '/parametric'
    | '/regression'
    | '/statistics'
    | '/surface-3d'
    | '/systems'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/geometry'
    | '/implicit'
    | '/linked'
    | '/multi'
    | '/notebook'
    | '/ode'
    | '/parametric'
    | '/regression'
    | '/statistics'
    | '/surface-3d'
    | '/systems'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/geometry'
    | '/implicit'
    | '/linked'
    | '/multi'
    | '/notebook'
    | '/ode'
    | '/parametric'
    | '/regression'
    | '/statistics'
    | '/surface-3d'
    | '/systems'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  GeometryRoute: typeof GeometryRoute
  ImplicitRoute: typeof ImplicitRoute
  LinkedRoute: typeof LinkedRoute
  MultiRoute: typeof MultiRoute
  NotebookRoute: typeof NotebookRoute
  OdeRoute: typeof OdeRoute
  ParametricRoute: typeof ParametricRoute
  RegressionRoute: typeof RegressionRoute
  StatisticsRoute: typeof StatisticsRoute
  Surface3dRoute: typeof Surface3dRoute
  SystemsRoute: typeof SystemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surface-3d': {
      id: '/surface-3d'
      path: '/surface-3d'
      fullPath: '/surface-3d'
      preLoaderRoute: typeof Surface3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regression': {
      id: '/regression'
      path: '/regression'
      fullPath: '/regression'
      preLoaderRoute: typeof RegressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametric': {
      id: '/parametric'
      path: '/parametric'
      fullPath: '/parametric'
      preLoaderRoute: typeof ParametricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ode': {
      id: '/ode'
      path: '/ode'
      fullPath: '/ode'
      preLoaderRoute: typeof OdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi': {
      id: '/multi'
      path: '/multi'
      fullPath: '/multi'
      preLoaderRoute: typeof MultiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linked': {
      id: '/linked'
      path: '/linked'
      fullPath: '/linked'
      preLoaderRoute: typeof LinkedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implicit': {
      id: '/implicit'
      path: '/implicit'
      fullPath: '/implicit'
      preLoaderRoute: typeof ImplicitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geometry': {
      id: '/geometry'
      path: '/geometry'
      fullPath: '/geometry'
      preLoaderRoute: typeof GeometryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  GeometryRoute: GeometryRoute,
  ImplicitRoute: ImplicitRoute,
  LinkedRoute: LinkedRoute,
  MultiRoute: MultiRoute,
  NotebookRoute: NotebookRoute,
  OdeRoute: OdeRoute,
  ParametricRoute: ParametricRoute,
  RegressionRoute: RegressionRoute,
  StatisticsRoute: StatisticsRoute,
  Surface3dRoute: Surface3dRoute,
  SystemsRoute: SystemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
