/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Surface3dRouteImport } from './routes/surface-3d'
import { Route as LinkedRouteImport } from './routes/linked'
import { Route as IndexRouteImport } from './routes/index'

const Surface3dRoute = Surface3dRouteImport.update({
  id: '/surface-3d',
  path: '/surface-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedRoute = LinkedRouteImport.update({
  id: '/linked',
  path: '/linked',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/linked': typeof LinkedRoute
  '/surface-3d': typeof Surface3dRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/linked': typeof LinkedRoute
  '/surface-3d': typeof Surface3dRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/linked': typeof LinkedRoute
  '/surface-3d': typeof Surface3dRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/linked' | '/surface-3d'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/linked' | '/surface-3d'
  id: '__root__' | '/' | '/linked' | '/surface-3d'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinkedRoute: typeof LinkedRoute
  Surface3dRoute: typeof Surface3dRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surface-3d': {
      id: '/surface-3d'
      path: '/surface-3d'
      fullPath: '/surface-3d'
      preLoaderRoute: typeof Surface3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linked': {
      id: '/linked'
      path: '/linked'
      fullPath: '/linked'
      preLoaderRoute: typeof LinkedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinkedRoute: LinkedRoute,
  Surface3dRoute: Surface3dRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
